export const colors = {
    primary: '#6470E1',      // Sign In button + links
    link: '#3B8FDD',          // checkbox label links
    brand: '#24589B',        // logo blue
    background: '#FFFFFF',
    inputBackground: '#F3F4F6',
    text: '#1F2024',
    textLabel: '#3D4150',
    placeholder: '#B8BCC8',
    icon: '#B8BCC8',
    error: '#E5484D',
    white: '#FFFFFF',
    bookingCardBackground: '#E1E4E8',
    bookingImageBackground: '#FFFFFF',
    bookingText: '#232629',
    bookingMutedText: '#9A9FA3',
    bookingAccent: '#1769ED',
    bookingIcon: '#8B9092',
    bookingAvatar: '#D94B77',
    bookingAvatarBorder: '#F0B7C7',
    bookingStatusWaiting: '#14D48A',
    bookingStatusDriving: '#252C2E',
    bookingHeroBackground: '#D9D9D9',
    bookingHeroButton: '#F6F7F8',
    bookingHeroOverlay: '#3B3D41',
    bookingDetailsText: '#1E2024',
    bookingDetailsMuted: '#777D84',
    bookingSpecBackground: '#E0E1E2',
    bookingSpecText: '#969CA1',
    bookingDateBorder: '#D8DDF9',
    bookingDateBackground: '#8F929B',
    bookingDateText: '#696E77',
    bookingUpdatesBackground: '#DCDDDD',
  };